### ISSUE TITLE
Getting started - Keycloak is unhealthy

### ISSUE THREAD

**Issue by skitana** [sermas-organization/sermas-toolkit-api#1]
Hello, 

I tried installing on Ubuntu 22 from Getting started web page and I get this error for keycloak container:
dependency failed to start: container sermas-toolkit-api-keycloak-1 is unhealthy

No particular errors can be seen in any container. All other containers are up and running.

Should docker-compose file be altered before running somehow?

Getting 502 error on 8080 port as well.
I am using a server for this, so I changed 0.0.0.0 for the ip of my server (locally).

![image](https://github.com/sermas-eu/sermas-toolkit-api/assets/47195706/d6148255-5903-4501-a994-ec20ab676dcc)

**Comment by lc-spxl** [comment]
Hi @skitana to confirm, you have already port 8080 in use correct ?

**Comment by skitana** [comment]
Hi @lc-spxl,
I started a brand new CT, 8080 port is not in use.
But, docker-compose.yaml file actually has 8080 for keycloak and for caddy, though keycloak port is not exposed...
The yaml file was not edited.
![image](https://github.com/sermas-eu/sermas-toolkit-api/assets/47195706/32c587cd-6a01-4171-9b7c-d10f4d108c54)

**Comment by lc-spxl** [comment]
This is not an issue,  keycloak has no exposed ports on the host while the proxy act as an api gateway.

Out of curiosity, have you tried finishing the tutorial or opening http://localhost:8080 ?

We will investigate the keycloak health issue

**Comment by tiagorribeiro24** [comment]
I tried messing around with this keycloak container and still can't make it healthy. I've also tried to make it work on windows (I was on ubuntu) and still the same error happens.
Can I get more information about which OS or tools have you installed to make this container/toolkit work?

Thank you.

**Comment by arghideutis** [comment]
It could be an issue with the recent version of keycloak. 
Can you please try changing the keycloak image version in the docker-compose.yml with the following:
```
keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
```
Thanks

**Comment by tiagorribeiro24** [comment]
Spot on. That was it. Thank you so much.

**Comment by skitana** [comment]
@lc-spxl  @arghideutis 
Thanks!
Keycloak version fixed it.
closing the thread
