### ISSUE TITLE
STT failed: Error: 400 Unrecognized file format

### ISSUE THREAD

**Issue by Kanthavel-Spindox** [sermas-organization/sermas-toolkit-api#4]
After setting up the default up following the tutorial, the speech interaction with the Avatar does not work.

The UI response "Sorry, could you retry?"

In the API, the following logs appear

api-1  | [Nest] 1  - 09/13/2024, 1:16:14 PM     LOG [SessionService] Creating session sessionId=9fc53245-35b9-4213-99ab-ad58edc20bec
api-1  | [Nest] 1  - 09/13/2024, 1:16:58 PM    WARN [LLMProviderService] Failed to fetch model for ollama: Model sermas-llama3 is not available from provider ollama
api-1  | [Nest] 1  - 09/13/2024, 1:17:01 PM     LOG [SessionAgentService] Received hearthbeat status=ready moduleId=avatar
api-1  | [Nest] 1  - 09/13/2024, 1:17:01 PM     LOG [SessionService] Creating session sessionId=731c9190-2922-4969-b801-507a2b110594
api-1  | [Nest] 1  - 09/13/2024, 1:17:04 PM    WARN [MonitorService] openai time elapsed 1563.912ms
api-1  | [Nest] 1  - 09/13/2024, 1:17:20 PM   ERROR [SpeechBrainService] Speech classification error: getaddrinfo EAI_AGAIN speechbrain
api-1  | [Nest] 1  - 09/13/2024, 1:17:22 PM   ERROR [STTProviderService] STT failed: Error: 400 Unrecognized file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']
api-1  |     at Function.generate (/app/node_modules/openai/src/error.ts:70:14)
api-1  |     at OpenAI.makeStatusError (/app/node_modules/openai/src/core.ts:397:21)
api-1  |     at OpenAI.makeRequest (/app/node_modules/openai/src/core.ts:460:24)
api-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
api-1  |     at async OpenAISpeechToText.text (/app/dist/apps/api/main.js:19345:31)
api-1  |     at async STTProviderService.convertToText (/app/dist/apps/api/main.js:19096:34)
api-1  |     at async DialogueSpeechService.convertToText (/app/dist/apps/api/main.js:18786:54)
api-1  | [Nest] 1  - 09/13/2024, 1:17:32 PM   ERROR [SpeechBrainService] Speech classification error: getaddrinfo EAI_AGAIN speechbrain
api-1  | [Nest] 1  - 09/13/2024, 1:17:33 PM   ERROR [STTProviderService] STT failed: Error: 400 Unrecognized file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']
api-1  |     at Function.generate (/app/node_modules/openai/src/error.ts:70:14)
api-1  |     at OpenAI.makeStatusError (/app/node_modules/openai/src/core.ts:397:21)
api-1  |     at OpenAI.makeRequest (/app/node_modules/openai/src/core.ts:460:24)
api-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
api-1  |     at async OpenAISpeechToText.text (/app/dist/apps/api/main.js:19345:31)
api-1  |     at async STTProviderService.convertToText (/app/dist/apps/api/main.js:19096:34)
api-1  |     at async DialogueSpeechService.convertToText (/app/dist/apps/api/main.js:18786:54)

**Comment by lc-spxl** [comment]
Closing, please reopen if still applies
